org.slf4j.simpleLogger.defaultLogLevel=info
org.slf4j.simpleLogger.log.org.hibernate=debug
org.slf4j.simpleLogger.log.org.hibernate.SQL=debug
org.slf4j.simpleLogger.log.org.hibernate.orm.jdbc.bind=trace
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss
